#!/usr/bin/env node
// Writes docs/STYLES-CATALOGUE.md from the style data: for every genre the
// research (what its players actually do, with the records that show it),
// then every feel with what it is about, who it is inspired by, its
// progression, key and tempo, and every part with the reasons it is written
// the way it is. Run after changing review/proposals*.js:
//     node tools/styles-doc.js
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
global.window = {}; global.console = console;
const GT = window.GT = {};
['js/theory.js', 'js/fretboard.js', 'js/parts.js', 'js/parts-guide-data.js', 'js/styles-base.js',
 'review/proposals.js', 'review/proposals-2.js', 'review/proposals-3.js', 'review/proposals-4.js',
 'review/proposals-more.js', 'review/proposals-easy.js', 'js/styles.js']
  .forEach(f => new Function('window', fs.readFileSync(path.join(root, f), 'utf8'))(window));

const text = html => String(html || '').replace(/<\/p>\s*<p>/g, '\n\n').replace(/<[^>]+>/g, '').replace(/[ \t]+/g, ' ').replace(/\n /g, '\n').trim();
const { STYLES, LIBRARY, GUIDE } = GT.styles;
const guideFor = (style, label) => GUIDE[`${style}/${label}`] || (GUIDE[style] && GUIDE[style].feel === label ? GUIDE[style] : null);
const lists = p => ['variants', 'fills', 'fillsOnChange', 'fillsOnStay', 'tails', 'pickups', 'stops', 'turnarounds', 'leads']
  .map(k => p[k] && p[k].length ? `${p[k].length} ${k}` : null).concat(p.turnaround ? ['a turnaround'] : []).concat(p.easy ? ['an easy version written for it'] : []).filter(Boolean).join(', ');

const out = [];
out.push('# The styles: what the research found', '',
  '_Generated by `tools/styles-doc.js` from the style data. Do not edit by hand; edit the proposals and run the tool. The method is in [STYLES.md](STYLES.md)._', '');
GT.review.genres.forEach(genre => {
  out.push(`## ${genre.name}`, '', text(genre.research), '');
  const feels = [...(genre.existing || []).map(e => ({ style: e.style, label: e.rename || e.label, was: e.label, verdict: e.verdict, inspired: null })),
                 ...(genre.additions || []).map(a => ({ style: a.style, label: a.label, inspired: a.inspired, why: a.why }))];
  feels.forEach(f => {
    const g = guideFor(f.style, f.label) || {};
    out.push(`### ${f.label}${f.was && f.was !== f.label ? ` (was "${f.was}")` : ''}`, '');
    if (g.progression) out.push(`Shown over ${g.progression.join(' · ')} in ${g.key}${g.mode ? ' ' + g.mode : ''} at ${g.tempo} BPM.`, '');
    if (f.inspired) out.push(`**Inspired by:** ${f.inspired}`, '');
    if (f.verdict) out.push(`**What changed:** ${text(f.verdict)}`, '');
    if (f.why) out.push(text(f.why), '');
    const parts = (LIBRARY[f.style] && LIBRARY[f.style][f.label]) || [];
    parts.forEach(p => {
      out.push(`- **${p.name}** — ${text(p.why || (g.parts && g.parts[p.name]) || '')}${lists(p) ? ` _(${lists(p)})_` : ''}`);
    });
    out.push('');
  });
});
out.push('## The engine proposals', '');
GT.review.engine.forEach(e => out.push(`### ${e.title}`, '', text(e.why), ''));
fs.writeFileSync(path.join(root, 'docs/STYLES-CATALOGUE.md'), out.join('\n'));
console.log('wrote docs/STYLES-CATALOGUE.md:', out.join('\n').length, 'chars');
